version: '3'

services:
  nginx:
    container_name: the-pong_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.aws
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - postgres
    networks:
      - the-pong-net
    environment:
      - TZ=Asia/Seoul

  postgres:
    image: postgres:15-alpine
    container_name: the-pong_postgres
    restart: unless-stopped
    networks:
      - the-pong-net
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  backend:
    container_name: the-pong_backend
    build: ./backend
    restart: unless-stopped
    networks:
      - the-pong-net
    depends_on:
      - postgres
    environment:
      CLIENT_APP_URL: ${PUBLIC_URL}
      SALT_ROUNDS: ${SALT_ROUNDS}
      CURSOR_SECRET: ${CURSOR_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GOOGLE_CB: ${GOOGLE_CB}
    volumes:
      - backend-uploads:/usr/src/app/uploads

  frontend:
    container_name: the-pong_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.aws
    restart: unless-stopped
    networks:
      - the-pong-net
    environment:
      PUBLIC_URL: ${PUBLIC_URL}
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    depends_on:
      - backend

networks:
  the-pong-net:

volumes:
  postgres:
  backend-uploads:
