version: '3'

services:
  nginx:
    container_name: the-pong_nginx_dev
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - backend
      - frontend
      - postgres
    networks:
      - the-pong-dev-net
    environment:
      - TZ=Asia/Seoul

  postgres:
    image: postgres:latest
    container_name: the-pong_postgres_dev
    restart: unless-stopped
    networks:
      - the-pong-dev-net
    ports:
      - 5432:5432
    volumes:
      - postgres-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - '5432'

  backend:
    container_name: the-pong_backend_dev
    build: ./backend
    restart: unless-stopped
    networks:
      - the-pong-dev-net
    ports:
      - '8000:8000'
      - '5555:5555'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      GOOGLE_CB: ${GOOGLE_CB}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_APP_URL: ${CLIENT_APP_URL}
    volumes:
      - backend-uploads-dev:/usr/src/app/uploads

  frontend:
    container_name: the-pong_frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    networks:
      - the-pong-dev-net
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      PUBLIC_URL: ${PUBLIC_URL}
      REACT_APP_AUTHOR: ${REACT_APP_AUTHOR}
      REACT_APP_TITLE: ${REACT_APP_TITLE}
      REACT_APP_DESCRIPTION: ${REACT_APP_DESCRIPTION}
    volumes:
      - ./frontend/src:/usr/src/app/src:ro
      - ./frontend/src/tests/__snapshots__:/usr/src/app/src/tests/__snapshots__:rw

networks:
  the-pong-dev-net:

volumes:
  postgres-dev:
  backend-uploads-dev:
