version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: the-pong_postgres_dev
    restart: unless-stopped
    networks:
      - the-pong-net
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"

  backend:
    container_name: the-pong_backend_dev
    build: ./backend
    restart: unless-stopped
    networks:
      - the-pong-net
    ports:
      - "8000:8000"
    depends_on:
      - postgres

networks:
  the-pong-net:

volumes:
  postgres:
