name: React app deployment
on:
  push:
    branches: ['develop']
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install --immutable --immutable-cache
      - name: Build
        working-directory: ./frontend
        run: yarn run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: frontend/build
