name: React app deployment
on:
  push:
    branches: ['develop']
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Setting .env
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          cat .env
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install --immutable --immutable-cache
      - name: Build
        working-directory: ./frontend
        run: yarn run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: frontend/build

